import type { PosterRule } from '@/types/rules';

export const DANISH_POSTER_RULES: PosterRule[] = [
  {
    id: 'height-minimum',
    category: 'placement',
    title: 'Minimumshøjde',
    description: 'Plakater skal hænges mindst 2,3 meter over vejbanen.',
    regulation: 'Vejlovens §84',
    enforcedBy: 'kommune',
  },
  {
    id: 'road-safety',
    category: 'safety',
    title: 'Trafiksikkerhed',
    description: 'Plakater må ikke dække for vejskilte, signaler eller på anden måde genere trafiksikkerheden.',
    regulation: 'Vejlovens §84',
    enforcedBy: 'politi',
  },
  {
    id: 'intersection-distance',
    category: 'placement',
    title: 'Afstand til kryds',
    description: 'Plakater må ikke hænges tættere end 10 meter fra et vejkryds.',
    regulation: 'Vejlovens §84',
    enforcedBy: 'kommune',
  },
  {
    id: 'poster-spacing',
    category: 'placement',
    title: 'Afstand mellem plakater',
    description: 'Der skal være mindst 50 meter mellem plakater fra samme parti.',
    regulation: 'Vejlovens §84',
    enforcedBy: 'kommune',
  },
  {
    id: 'hanging-period',
    category: 'timing',
    title: 'Ophængningsperiode',
    description: 'Plakater må tidligst ophænges den 4. lørdag før valgdagen.',
    regulation: 'Vejlovens §84',
    enforcedBy: 'kommune',
  },
  {
    id: 'removal-deadline',
    category: 'removal',
    title: 'Nedtagningsfrist',
    description: 'Plakater skal være nedtaget senest 8 dage efter valgdagen.',
    regulation: 'Vejlovens §84',
    enforcedBy: 'kommune',
  },
  {
    id: 'private-property',
    category: 'placement',
    title: 'Privat ejendom',
    description: 'Plakater må ikke ophænges på privat ejendom uden tilladelse.',
    regulation: 'Vejlovens §84',
    enforcedBy: 'kommune',
  },
  {
    id: 'contact-info',
    category: 'size',
    title: 'Kontaktoplysninger',
    description: 'Alle valgplakater skal indeholde navn, adresse og telefonnummer på den ansvarlige.',
    regulation: 'Vejlovens §84',
    enforcedBy: 'kommune',
  },
  {
    id: 'motorway-prohibition',
    category: 'placement',
    title: 'Motorvejsforbud',
    description: 'Plakater må ikke ophænges langs motorveje og motortrafikveje.',
    regulation: 'Vejlovens §84',
    enforcedBy: 'vejdirektoratet',
  },
  {
    id: 'max-size',
    category: 'size',
    title: 'Maksimal størrelse',
    description: 'Plakater må højst være 0,8 m² i areal.',
    regulation: 'Vejlovens §84',
    enforcedBy: 'kommune',
  },
];
